import type { Metadata } from "next";
import Link from 'next/link'
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative min-h-screen">
          {/* Background Video */}
          <video
            autoPlay
            loop
            muted
            className="opacity-40 fixed top-0 left-0 w-full h-full object-cover z-0"
          >
            <source src="/bg.mp4" type="video/mp4" />
          </video>
          
          <div 
            style={{
            position: 'absolute',
            top: 0,
            left: 0,
            width: '100%',
            height: '100%',
            backdropFilter: 'blur(15px)',
            zIndex: 2,
            }}/>

          <nav className="absolute top-0 w-full z-50">
          <div className="max-w-5xl mx-auto px-4 py-4">
            <div className="flex justify-center pt-2 items-center gap-16 space-x-8">
              <Link 
                href="/about" 
                className="text-sm transition-colors"
              >
                About
              </Link>
              <Link 
                href="/works" 
                className="text-sm transition-colors"
              >
                Works
              </Link>
              <Link 
                href="/contact" 
                className="text-sm transition-colors"
              >
                Contact
              </Link>
            </div>
          </div>
        </nav>
          <main className="relative z-10 container mx-auto px-6 py-8">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
